### ISSUE TITLE
crash running a non-specific search.

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#2400]
I ran an analysis that includes spectra averaging, GPTMD and search.
The crash occurred during the search stage, giving a "key=10" error. 
see the attached file.

Thanks!
David.
[results.txt](https://github.com/user-attachments/files/16676304/results.txt)

**Comment by trishorts** [comment]
being addressed in https://github.com/smith-chem-wisc/MetaMorpheus/pull/2401

**Comment by trishorts** [comment]
David, will you try this build and see if it solves your problem?
https://ci.appveyor.com/api/buildjobs/qbksajlqjoxeyp0k/artifacts/MetaMorpheusInstaller.msi

**Comment by Dmorgen** [comment]
Will do, thanks!
D.

**Comment by acesnik** [comment]
🤖 Still current, so leaving this open — but the picture has narrowed. The crash in this log is fixed in one of the two places it can happen, and still present in the other.

**What landed.** #2401 was closed without merging; the fix that reached master was #2453 (2024-12-16), which added a duplicate-key guard to the **C-terminal** branch of `NonSpecificEnzymeSearchEngine.Accepts`:

```csharp
if (terminalMod != null && !updatedMods.Keys.Contains(startResidue - 1))
```

That's the build that was tried here, and it did clear this crash — the follow-up report (#2454, now closed) is the same run getting as far as quantification.

**What's left.** The N-terminal branch has the same `Add` with no guard (`NonSpecificEnzymeSearchEngine.cs:361-364` on master):

```csharp
if (terminalMod != null)
{
    updatedMods.Add(endResidue, terminalMod);
}
```

Invoking `Accepts` directly with `singleN` / `CleavageSpecificity.None` / min length 5, one variable `Anywhere` mod and one variable `C-terminal` mod reproduces it:

```
ArgumentException: An item with the same key has already been added. Key: 10
```

Reachability: retained keys satisfy `mod.Key < FragmentNumber + 2` while `endResidue = OneBasedStartResidue + FragmentNumber - 1`, so it needs `OneBasedStartResidue <= 2` — the N-terminal peptides of every protein, which a non-specific search generates throughout. The route is *variable* terminal mods rather than database-annotated ones: a peptide-C-terminal mod annotated at an internal position is dropped by the `Protein` constructor, but `GetTerminalModPositions`'s variable-mod branch applies them at every matching residue with no terminus check.

**Worth a look before adding the guard.** `endResidue` is an absolute protein coordinate being used as a key in a peptide-relative mod dictionary, and mirroring the C-terminal guard would stop the crash without touching that. Measured through the same direct invocation:

| Case | Truncated peptide | Valid keys | Key used | Result |
|---|---|---|---|---|
| start=1, fragment 10 | length 10 | 1–12 | 10 | mod placed on residue 9 (an alanine), not the C-terminal K; mass correct |
| start=5, fragment 6 | length 6 | 1–8 | 10 | out of range — `FullSequence` is `AAAAAK` with no mod shown, while `MonoisotopicMass` 543.30166 includes the +42.011 |

The second row is a match whose reported sequence does not account for its own mass. The C-terminal branch builds its key the same way (`startResidue - 1`), so this isn't specific to one branch.

**Not verified:** all of the above is synthetic input through a direct call to `Accepts`. I have not run a full search and have not traced what any of it writes to `.psmtsv`, so the practical effect on results is unknown. Given the coordinate question, whoever knows what these keys were meant to be is better placed to pick the fix than a guard mirroring the existing one.
